### ISSUE TITLE
LSP formatting and prettier

### ISSUE THREAD

**Issue by gegoune** [lukastl21/dotfiles#1]
Hi Lukas, great approach to formatting, works really well, thanks a lot!

I have one tiny problem with prettier though. You do, and me too, hardcode configuration for it that is then passed to efm. How would you add functionality to read `.prettierrc` should there be one in git root and use that instead of parameters passed from neovim's configuration?

Thanks!

**Comment by lukas-reineke** [comment]
prettier has an option for this, `--config-precedence`. When you set this to `prefer-file`, prettier will use the cli arguments only if there is no `.prettierrc`, if there is, the file takes priority and all cli arguments are ignored.
So you can hardcode cli arguments in vim, but they are not used in a project with different settings. Works great for me.

**Comment by gegoune** [comment]
Argh, It was already there, thank you so much Lukas!
