### ISSUE TITLE
Buffer number is nil

### ISSUE THREAD

**Issue by pedropmedina** [lukastl21/dotfiles#2]
Hey Lukas, I noticed that on the latest neovim update the bufnr in the handlers returns nil making this ```bufnr == vim.api.nvim_get_current_buf()``` false. Have you encountered this issue or am I missing something here? - Thanks

```lua
vim.lsp.handlers["textDocument/formatting"] = function(err, _, result, _, bufnr)    
  if err ~= nil or result == nil then  return  end    
  if not vim.api.nvim_buf_get_option(bufnr, "modified") then      
      local view = vim.fn.winsaveview()        
      vim.lsp.util.apply_text_edits(result, bufnr) 
      vim.fn.winrestview(view)        
      if bufnr == vim.api.nvim_get_current_buf() then            
        vim.cmd [[noautocmd :update]]            
        vim.cmd [[GitGutter]]       
      end    
  end
end
```

**Comment by lukas-reineke** [comment]
I opened a PR to fix this in Neovim https://github.com/neovim/neovim/pull/14641

But it's safe to remove the if check if you don't save and immediately jump to a different buffer.
