### ISSUE TITLE
How you implement format asynchronously?

### ISSUE THREAD

**Issue by ayamir** [lukastl21/dotfiles#4]
Recently I noticed that [format.nvim](https://github.com/lukas-reineke/format.nvim) is deprecated and your [post](https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/) on reddit.
So I start to configure format with [efm-langserver](https://github.com/mattn/efm-langserver).
But I find nothing indicates it can provide async format.
I tried configuring efm to do format and lint, but its effect is not very well.
I don't know whether my config is wrong or not:
https://github.com/ayamir/nvimdots/commit/b5a0b31de3d2a0fcad5120eb6d9b7cf0d6a84d2e

**Comment by lukas-reineke** [comment]
All LSP serve can do async formatting. You have to change `vim.lsp.buf.formatting_sync()` to `vim.lsp.buf.formatting()` here
https://github.com/ayamir/nvimdots/commit/b5a0b31de3d2a0fcad5120eb6d9b7cf0d6a84d2e#diff-f909cd5a5e972ea5d43a2a33cbacf16a7ef328ac977a2419d3ebd4a63afbedaaR53

And also don't remove formatting from the capabilities.
https://github.com/ayamir/nvimdots/commit/b5a0b31de3d2a0fcad5120eb6d9b7cf0d6a84d2e#diff-7ace36393c377fdcfec306aa7cfbb177619270827fbf245d76b00cb06cc2f281R46-R48

The rest looks correct I think.

**Comment by ayamir** [comment]
Thanks for your reply!
I corrected my config follow your instruction.
But it will freeze when I try formatting a big c file:

https://user-images.githubusercontent.com/61657399/148776058-8b535bae-26d5-433c-8355-9962e6fd597b.mp4

This file is from [here](http://dl.suckless.org/dwm/dwm-6.3.tar.gz)

**Comment by lukas-reineke** [comment]
Even with no configuration at all, `vim.lsp.buf.formatting()` will not block.
Try to call this directly with `:lua vim.lsp.buf.formatting()` and see what happens.

**Comment by ayamir** [comment]
If I remove relevant settings about `vim.lsp.handlers["textDocument/formatting"]`, this operation will freeze nvim directly.
Maybe because there two clients attached to this buffer?
![图片](https://user-images.githubusercontent.com/61657399/148874986-29d1c45d-6432-4be5-ac03-ca7b17d1e401.png)
The same result occurred though I removed settings about `efm` or `clangd` installed by `nvim-lsp-installer`.
My config is [here](https://github.com/ayamir/nvimdots/blob/dev/lua/modules/completion/lsp.lua) btw.

**Comment by lukas-reineke** [comment]
Two clients is fine.

Try to remove parts of your config until `vim.lsp.buf.formatting()` does not freeze.
It should never happen, I don't know why it would.

**Comment by ayamir** [comment]
The reason is `treesitter` ...
Maybe I need to disable it then format and then enable it.

**Comment by lukas-reineke** [comment]
that's very odd. You should open an issue in the neovim repo if you know how to reproduce it.

**Comment by ayamir** [comment]
It costs about 3 seconds to format without `treesitter` rather than 37 seconds with `treesitter`.
It has nothing to do with `treesitter` plugins, just depends on whether the `c` parser has been installed or not.

**Comment by lukas-reineke** [comment]
This should definitely not happen, but I can't help you with that.
Open an issue in neovim

**Comment by ayamir** [comment]
Thanks.
